# Generated by Django 6.0 on 2026-01-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, help_text='Teacher reply to this comment', null=True),
        ),
    ]
