# Generated by Django 6.0 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comments-videos/'),
        ),
    ]
