# Generated by Django 6.0.3 on 2026-03-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_comment_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
